cli/.dockerignore, cli/Dockerfile, cli/src/plz/cli/input_data.py, cli/src/plz/cli/log.py, cli/src/plz/cli/run_execution_operation.py, services/controller/.dockerignore, services/controller/Dockerfile, services/controller/Pipfile, services/controller/Pipfile.lock, services/controller/src/plz/controller/configuration.py, services/controller/src/plz/controller/images/local.py, test/run
This speeds up both building the CLI and controller, and the executions.
It also restructures a bunch of stuff in the `run` command to log timing information so I could figure out the above.
Turns out that the Python Docker client takes _ages_ to figure out authentication for building/pulling, which sucks. I would like to send them a patch upstream at some point but for now, we can just bypass it and use the Docker socket directly.
=> Make the tests faster by speeding up Docker builds.

test/run
It's worth noting that this doesn't actually work. The tests fail. This
has highlighted a number of weird quirks in our controller when one
test cleans up at just the wrong time. Containers go missing, 404s go
flying, calamity ensues.
I think these problems will be addressed by making harvesting a
background job, so we can leave it here and maybe switch to this mode as
the default when it's stable.
Here's an example of the errors we might get running tests in parallel:
[2018-04-18 18:53:14,358] ERROR in app: Exception on /executions/bd30ac06-4339-11e8-8805-6bbc9a67228c/logs [GET]
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 225, in _raise_for_status
response.raise_for_status()
File …
=> Test: Allow tests to run in parallel.

cli/src/plz/cli/run_execution_operation.py, services/controller/config/_aws.conf, services/controller/playbook.yml, services/controller/src/plz/controller/configuration.py, services/controller/src/plz/controller/exceptions.py, services/controller/src/plz/controller/images/ecr.py, services/controller/src/plz/controller/images/images_base.py, services/controller/src/plz/controller/images/local.py, services/controller/src/plz/controller/main.py
- authenticate with ECR before building so we can pull the image
- pull the image every time (so this bug gets triggered faster)
- this is useful anyway, because you don't want to get a stale base image
- debug-level logging for building (so I could find the problem)
- filter out progress indicators for building, pushing and pulling
=> Controller: Make sure we can pull base images.

cli/src/plz/cli/run_execution_operation.py
We use `/src` in both our base images. Switching to `/app` at this point is problematic (and silly). It causes problems when running node.js-based software, as the dependencies are typically installed to `$PWD/node_modules`, and changing `$PWD` makes them unavailable.
=> CLI: Change the working directory inside the image to /src.

cli/src/plz/cli/main.py, cli/src/plz/cli/server.py, cli/test/test/plz/cli/server_test.py
And then a bunch of refactoring in _server.py_ to make it simpler.
=> CLI: Move the HTTP error-handling to the Server class.

cli/src/plz/cli/run_execution_operation.py, services/controller/src/plz/controller/arbitrary_object_json_encoder.py, services/controller/src/plz/controller/containers.py, services/controller/src/plz/controller/db_storage.py, services/controller/src/plz/controller/exceptions.py, services/controller/src/plz/controller/execution.py, services/controller/src/plz/controller/execution_metadata.py, services/controller/src/plz/controller/instances/aws/ec2_instance.py, services/controller/src/plz/controller/instances/aws/ec2_instance_group.py, services/controller/src/plz/controller/instances/docker.py, services/controller/src/plz/controller/instances/instance_base.py, services/controller/src/plz/controller/instances/localhost.py, services/controller/src/plz/controller/main.py, services/controller/src/plz/controller/redis_db_storage.py, services/controller/src/plz/controller/results/local.py, services/controller/src/plz/controller/results/results_base.py
Return information about the spot instance request and the instance state when the worker is unreachable, or when the instance is not running.
Generalise the logic "if there are results, get things from there, otherwise from get them from the instance" in an `Execution` class.
=> Controller: write tombstones for terminated instances

plz
`-f` means something different on BSD. Instead, we use `realpath`.
=> Dev: `readlink -f`  doesn't work on macOS or BSD.

docker-compose.base.yml, services/controller/playbook.yml, vars.mk
We can't trust the docker cache when changing AMIs
=> Persist redis db in the cache volume instead of a docker volume

machines/ml/prepare.yml, services/controller/src/plz/controller/instances/aws/ec2_instance_group.py
- When creating the AMI, restart packer instance after updating the packages
- Do not execute startup.yml in workers.
It basically sets up a cache. In the worker we are discarding
the cache so it's useless. We want to implement some sort of
cache eventually but the right way to do it is to create snapshots
with /var/lib/docker dirs with the images, and attach them to workers
(having different stuff in the cache every time goes against
reproducibility, and user code in the images costs usually nothing to
transfer)
=> Controller: fix worker setup

services/controller/src/plz/controller/configuration.py, services/controller/src/plz/controller/images/ecr.py, services/controller/src/plz/controller/images/images_base.py, services/controller/src/plz/controller/images/local.py
Otherwise after some time we start seeing weird authentication errors.
The errors go off when the controller is restarted (without restarting the Docker daemon), which suggests that something is wrong with the state of the (clients of the) controller
=> Controller: for images, recreate ECR and docker clients in each login

services/controller/src/plz/controller/instances/aws/ec2_instance_group.py
If you don't include #!/bin/sh at the beginning, the UserData is not treated as a script
=> Fix execution of nvidia-persistenced during startup

cli/setup.py
Flask is required for nosetests to run. Version bumps make it easier to
work with nixpkgs.
=> Bump requests & urllib dep, add flask

.gitignore, cli/src/plz/controller/api, plz
Previous to this there was a hacky hack to create a symlink
to the controller code if it didn't exist. This worked as to run
the `plz` script to execute the code directly, but was breaking
`make check` for the cli, as the pipenv for the cli lacked the
modules required by the controller. If we have a link to the
controller api instead, everything works fine.
Underlying all this is the fact that if there are several
paths to a module in the pythonpath, the python interpreter
will pick only one of them (as opposed to java). So we cannot
put the api in a directory outside the controller and the api code
under plz.controller.api (as we'd do in java) as only either the
controller or the api would be picked
=> CLI: make the controller api (and only the api) available to the cli

examples/python/plz.config.json, examples/pytorch/plz.config.json
It seems you can't get t2 spot instances any more
=> Examples: use t3 instances instead of t2

README.md, cli/src/plz/cli/configuration.py, examples/python/plz.config.json, examples/pytorch/plz.config.json, examples/pytorch/plz.cuda.config.json, services/controller/src/plz/controller/main.py, test/controller/src/utils.py, test/run-end-to-end-test
This means we don't have to specify the max bid price, which also means the CLI works for local runs without having to set this value for no reason.
=> Default to on-demand instances.

start_local_controller
To be extra sure. Again, it was there for aws, not having it here was simply overlooking.
=> start_local_controller: use --no-build for docker compose

services/controller/src/plz/controller/controller_impl.py, services/controller/src/plz/controller/execution_composition.py, services/controller/src/plz/controller/execution_metadata.py, services/controller/src/plz/controller/results/local.py
Now we have a single `if parallel_instance`, and it's not in the controller object :)
=> Controller: remove `if parallel_instances` logic from controller object

cli/src/plz/cli/controller_proxy.py, services/controller/src/plz/controller/results/local.py
- Removed lock timeout. For outputs taking more than one minute to download, it was timing out and then failing when releasing the lock. Downloading in the meantime could cause getting partial output
- Improved how long responses are read from the CLI. It was reading small amounts at a time, implying a lot of writes, a huge waste of time. This might be due to a change in the underlying libraries, as we were having big outputs before and this wasn't a problem
=> plz-output: improve performance and reliability

.circleci/config.yml, cli/Pipfile.lock, services/controller/Pipfile.lock, services/controller/src/plz/controller/instances/aws/ec2_instance_group.py
The version of Jinja2 has a security vulnerability (reported by GitHub),
so I thought I'd just upgrade everything.
=> Upgrade all dependencies.

cli/src/plz/cli/list_context_operation.py, cli/src/plz/cli/snapshot.py, test/end-to-end/source/gitignored-files/main.py
When computing included/excluded files we were using a utility
function from the docker libraries, but it's very powerful
(heavy pattern matching) and then too slow if you happen to
have many files (even if ignored) it was taking quite some
noticeable time.
The logic is now simple and we are using just python globs,
which should be easier for the user to play with as well,
in case they are debugging their exclude/include specs
=> Cli: fix context generation

cli/setup.py
The current version of requests doesn't support urllib3 1.25
=> Cli: temporarily restrict the version of urllib3
